mod app;
pub mod editor;
mod highlight;
mod input_box;
mod input_modal;
mod meeting_modal;
mod meetings_view;
mod reflections_view;
mod splash;
mod status_modal;
mod summaries_view;
mod summary_view;
mod timeline_view;
mod todo_list;
mod version;
pub use app::run;
